package com.matuszak.engineer.domain.project.model;

public enum ProjectRole {
    PROJECT_MANAGER, OWNER, GRAPHICS_DESIGNER,
    SENIOR_JAVA_DEVELOPER, JUNIOR_JAVA_DEVELOPER, REGULAR_JAVA_DEVELOPER,
    SENIOR_C_DEVELOPER, JUNIOR_C_DEVELOPER, REGULAR_C_DEVELOPER,
    SENIOR_JAVASCRIPT_DEVELOPER, JUNIOR_JAVASCRIPT_DEVELOPER, REGULAR_JAVASCRIPT_DEVELOPER,
    FRONTEND_DEVELOPER, BACKEND_DEVELOPER,
}
